{
  "data": {
    "biographyCollection": {
      "items": [
          "description": {
            "json": {
              "nodeType": "document",
              "content": [
                {
                  "nodeType": "paragraph",
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "Sed lacinia, dolor a malesuada suscipit\:",
                    }
                  ],
                },
                {
                  "nodeType": "unordered-list",
                  "content": [
                    {
                      "nodeType": "list-item",
                      "content": [
                        {
                          "nodeType": "paragraph",
                          "content": [
                            {
                              "nodeType": "text",
                              "value": "consectetur adipiscing elit",
                            }
                          ],
                        }
                      ],
                    },
                    {
                      "nodeType": "list-item",
                      "content": [
                        {
                          "nodeType": "paragraph",
                          "content": [
                            {
                              "nodeType": "text",
                              "value": "a malesuada suscipit",
                            }
                          ],
                        }
                      ],
                  ],
                },
              ]
            },
          }
        }
      ]
    }
  }
}